include pyrsp

diff --git a/.direnv/bin/nix-direnv-reload b/.direnv/bin/nix-direnv-reload
--- a/.direnv/bin/nix-direnv-reload
+++ b/.direnv/bin/nix-direnv-reload
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
-dir="$(realpath $(dirname ${BASH_SOURCE[0]})/../..)"
-_nix_direnv_force_reload=1 direnv exec "$dir" true
-direnv reload
-# direnv reload updates the mtime of .envrc. Also update the timestamp of the
-# profile_rc file to keep track that we actually are up to date.
-touch $dir/.direnv/{nix,flake}-profile-*.rc
+set -e
+if [[ ! -d "/home/ken/Codes/School/ics/pa" ]]; then
+  echo "Cannot find source directory; Did you move it?"
+  echo "(Looking for "/home/ken/Codes/School/ics/pa")"
+  echo 'Cannot force reload with this script - use "direnv reload" manually and then try again'
+  exit 1
+fi
 
+# rebuild the cache forcefully
+_nix_direnv_force_reload=1 direnv exec "/home/ken/Codes/School/ics/pa" true
+
+# Update the mtime for .envrc.
+# This will cause direnv to reload again - but without re-building.
+touch "/home/ken/Codes/School/ics/pa/.envrc"
+
+# Also update the timestamp of whatever profile_rc we have.
+# This makes sure that we know we are up to date.
+touch -r "/home/ken/Codes/School/ics/pa/.envrc" "/home/ken/Codes/School/ics/pa/.direnv"/*.rc
